
//begin the strings
#define STR_OK 0
#define STR_CANCEL 1
#define STR_YES 2
#define STR_NO 3
#define STR_OPTIONS 4
#define STR_SELECT 5
#define STR_BIANJI 6
#define STR_BACK 7
#define STR_CHARU 8
#define STR_TIAOZHUAN 9
#define STR_DAOHANG 10
#define STR_SETQI 11
#define STR_SETZHONG 12
#define STR_FUZHI 13
#define STR_ZHANTIE 14
#define STR_QUXIAOXUANZE 15
#define STR_WENJIAN 16
#define STR_NEW 17
#define STR_DAKAI 18
#define STR_BAOCUN 19
#define STR_LINGCUNWEI 20
#define STR_PRINTLOG 21
#define STR_DABAO 22
#define STR_QITA 23
#define STR_SET 24
#define STR_SETCOL 25
#define STR_YUNXING 26
#define STR_ABOUT 27
#define STR_EXIT 28
#define STR_HELP 29
#define STR_NEWNULL 30
#define STR_NEWFORM 31
#define STR_NEWPRO 32
#define STR_NEWHELLO 33
#define STR_NEWMODE 34
#define STR_PRONAMEPUT 35
#define STR_PRONAME 36
#define STR_FOUNDOK 37
#define STR_FOUNDNO 38
#define STR_YEAR 39
#define STR_MONTH 40
#define STR_SUNDAY 41
#define STR_MONDAY 42
#define STR_TUESDAY 43
#define STR_WENDESAY 44
#define STR_THURSDAY 45
#define STR_FRIDAY 46
#define STR_SATURDAY 47
#define STR_ZBT 48
#define STR_GUANYUDT 49
#define STR_BANGZHUDT 50
#define STR_SHURUTEXT 51
#define STR_SHURUHANG 52
#define STR_SHURUNAME 53
#define STR_MSG 54
#define STR_MENU 55
#define STR_FILE 56
#define STR_OPEN 57
#define STR_SAVE 58
#define STR_SAVETO 59
#define STR_CLOSE 60
#define STR_CLOSES 61
#define STR_INPUTNAME 62
#define STR_SAVESUC 63
#define STR_SAVEFAI 64
#define STR_INPUT 65
#define STR_OPENFILE 66
#define STR_OPENDIR 67
#define STR_NEWDIR 68
#define STR_CUT 69
#define STR_COPYFILE 70
#define STR_PASTE 71
#define STR_REMOVE 72
#define STR_RETURN 73
#define STR_REALREMOVE 74
#define STR_STARTREMOVE 75
#define STR_STARTFIND 76
#define STR_WARNING1 77
#define STR_RENAME 78
#define STR_NOTFILE 79
#define STR_CNOWNAME 80
#define STR_FONT0 81
#define STR_FONT1 82
#define STR_FONT2 83
#define STR_FONT12 84
#define STR_FONT16 85
#define STR_HEAP_SIZE 86

#define RES_STRING_COUNT 87
