#ifndef _MAINWND_H
#define _MAINWND_H

#include "window.h"

//child window ids
enum
{
	MAINWND_RECT = 1,
	MAINWND_EDIT,
	MAINWND_BUTTON,
	MAINWND_FLASHBOX,
	MAINWND_LABEL,
	MAINWND_COMBO1,
	MAINWND_COMBO2,
	MAINWND_TOOLBAR,
	MAINWND_PROGBAR,
	MAINWND_OPTMENU,
	MAINWND_ZBT,
	MAINWND_CHARU,
	MAINWND_EDITORU,
	MAINWND_TIAOZHUAN,
	MAINWND_LINGCUN,
	MAINWND_NEWJ,

	MAINWND_GUANYUDT,
	MAINWND_GUANYUGJ,
	MAINWND_GUANYUBT,


	MAINWND_SETBT,
	MAINWND_SETGJ,
	MAINWND_SETZHK,
	MAINWND_SETZT,
	MAINWND_SETHEAP,

	MAINWND_BANGZHUBT,
	MAINWND_BANGZHUGJ,
	MAINWND_BANGZHUDT
};


LRESULT MAINWND_WndProc(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT MENUWND_WndProc(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT SUBMENUWND_WndProc(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT MAINWND_GuanYu(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT MAINWND_BangZhu(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT MAINWND_Set(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);

#endif
