[information]
projectname=print.mpr
filename=mrpshop.mrp
appname=mrp应用商店1.0
appid=30001
version=101
visible=1
cpu=3
vendor=风的影子
output=mrpshop.mrp
description=net应用商店 mrp.yzjlb.net 风的影子制作 2021.07.01
include=..\modules\,${MRPBUILDER_HOME}\..\include\
config=mtk240

[config_mtk240]
output=mrpshop.mrp
bmp_mode=normal
plat=mtk

[files]
file01 = main.c
file100 = buffer.c
file101 = httpparser.c
file102 = url_docode.c
file103 = cJSON.c
file104 = filelist.c
file105 = mpc.c